# Form implementation generated from reading ui file 'bakeryOrders.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowsBakery(object):
    def setupUi(self, WindowsBakery):
        WindowsBakery.setObjectName("WindowsBakery")
        WindowsBakery.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WindowsBakery)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(-5, -9, 821, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(30)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        WindowsBakery.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowsBakery)
        QtCore.QMetaObject.connectSlotsByName(WindowsBakery)

    def retranslateUi(self, WindowsBakery):
        _translate = QtCore.QCoreApplication.translate
        WindowsBakery.setWindowTitle(_translate("WindowsBakery", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowsBakery = QtWidgets.QMainWindow()
    ui = Ui_WindowsBakery()
    ui.setupUi(WindowsBakery)
    WindowsBakery.show()
    sys.exit(app.exec())
