# Form implementation generated from reading ui file 'BakeryOrders.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_BakeryOrders(object):
    def setupUi(self, Window_BakeryOrders):
        Window_BakeryOrders.setObjectName("Window_BakeryOrders")
        Window_BakeryOrders.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Window_BakeryOrders)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(-5, -9, 821, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(30)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        Window_BakeryOrders.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_BakeryOrders)
        QtCore.QMetaObject.connectSlotsByName(Window_BakeryOrders)

    def retranslateUi(self, Window_BakeryOrders):
        _translate = QtCore.QCoreApplication.translate
        Window_BakeryOrders.setWindowTitle(_translate("Window_BakeryOrders", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_BakeryOrders = QtWidgets.QMainWindow()
    ui = Ui_Window_BakeryOrders()
    ui.setupUi(Window_BakeryOrders)
    Window_BakeryOrders.show()
    sys.exit(app.exec())
