# Form implementation generated from reading ui file 'bakery.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowBakery(object):
    def setupUi(self, WindowBakery):
        WindowBakery.setObjectName("WindowBakery")
        WindowBakery.resize(1238, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowBakery.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowBakery)
        self.centralwidget.setObjectName("centralwidget")
        self.label_OLAP_dayWeek_cakes = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek_cakes.setEnabled(False)
        self.label_OLAP_dayWeek_cakes.setGeometry(QtCore.QRect(20, 380, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek_cakes.setFont(font)
        self.label_OLAP_dayWeek_cakes.setObjectName("label_OLAP_dayWeek_cakes")
        self.label_OLAP_dayWeek_pie = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek_pie.setEnabled(False)
        self.label_OLAP_dayWeek_pie.setGeometry(QtCore.QRect(20, 280, 531, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek_pie.setFont(font)
        self.label_OLAP_dayWeek_pie.setObjectName("label_OLAP_dayWeek_pie")
        self.lineEdit_OLAP_dayWeek_pie = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek_pie.setEnabled(False)
        self.lineEdit_OLAP_dayWeek_pie.setGeometry(QtCore.QRect(20, 310, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek_pie.setFont(font)
        self.lineEdit_OLAP_dayWeek_pie.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek_pie.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek_pie.setObjectName("lineEdit_OLAP_dayWeek_pie")
        self.lineEdit_OLAP_dayWeek_bakery = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek_bakery.setEnabled(False)
        self.lineEdit_OLAP_dayWeek_bakery.setGeometry(QtCore.QRect(20, 210, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek_bakery.setFont(font)
        self.lineEdit_OLAP_dayWeek_bakery.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek_bakery.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek_bakery.setObjectName("lineEdit_OLAP_dayWeek_bakery")
        self.label_OLAP_P = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_P.setGeometry(QtCore.QRect(20, 80, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_P.setFont(font)
        self.label_OLAP_P.setObjectName("label_OLAP_P")
        self.btn_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cakes.setGeometry(QtCore.QRect(860, 250, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cakes.setFont(font)
        self.btn_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_cakes.setCheckable(False)
        self.btn_cakes.setObjectName("btn_cakes")
        self.lineEdit_OLAP_P = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_P.setEnabled(False)
        self.lineEdit_OLAP_P.setGeometry(QtCore.QRect(20, 110, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_P.setFont(font)
        self.lineEdit_OLAP_P.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_P.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_P.setObjectName("lineEdit_OLAP_P")
        self.btn_path_ost_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_ost_cakes.setGeometry(QtCore.QRect(740, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_ost_cakes.setFont(font)
        self.btn_path_ost_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_ost_cakes.setCheckable(False)
        self.btn_path_ost_cakes.setObjectName("btn_path_ost_cakes")
        self.btn_path_ost_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_ost_filling.setGeometry(QtCore.QRect(740, 610, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_ost_filling.setFont(font)
        self.btn_path_ost_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_ost_filling.setCheckable(False)
        self.btn_path_ost_filling.setObjectName("btn_path_ost_filling")
        self.btn_path_OLAP_P = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_OLAP_P.setGeometry(QtCore.QRect(740, 110, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_OLAP_P.setFont(font)
        self.btn_path_OLAP_P.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_OLAP_P.setCheckable(False)
        self.btn_path_OLAP_P.setObjectName("btn_path_OLAP_P")
        self.label_settings_title = QtWidgets.QLabel(self.centralwidget)
        self.label_settings_title.setGeometry(QtCore.QRect(20, 10, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.label_ost_cakes = QtWidgets.QLabel(self.centralwidget)
        self.label_ost_cakes.setEnabled(False)
        self.label_ost_cakes.setGeometry(QtCore.QRect(20, 480, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_ost_cakes.setFont(font)
        self.label_ost_cakes.setObjectName("label_ost_cakes")
        self.lineEdit_OLAP_dayWeek_cakes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek_cakes.setEnabled(False)
        self.lineEdit_OLAP_dayWeek_cakes.setGeometry(QtCore.QRect(20, 410, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek_cakes.setFont(font)
        self.lineEdit_OLAP_dayWeek_cakes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek_cakes.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek_cakes.setObjectName("lineEdit_OLAP_dayWeek_cakes")
        self.btn_path_dayWeek_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek_cakes.setGeometry(QtCore.QRect(740, 410, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek_cakes.setFont(font)
        self.btn_path_dayWeek_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek_cakes.setCheckable(False)
        self.btn_path_dayWeek_cakes.setObjectName("btn_path_dayWeek_cakes")
        self.lineEdit_ost_filling = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ost_filling.setEnabled(False)
        self.lineEdit_ost_filling.setGeometry(QtCore.QRect(20, 610, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_ost_filling.setFont(font)
        self.lineEdit_ost_filling.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_ost_filling.setStyleSheet("padding-left: 5px")
        self.lineEdit_ost_filling.setObjectName("lineEdit_ost_filling")
        self.label_OLAP_dayWeek_bakery = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek_bakery.setGeometry(QtCore.QRect(20, 180, 511, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek_bakery.setFont(font)
        self.label_OLAP_dayWeek_bakery.setObjectName("label_OLAP_dayWeek_bakery")
        self.btn_others = QtWidgets.QPushButton(self.centralwidget)
        self.btn_others.setGeometry(QtCore.QRect(860, 470, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_others.setFont(font)
        self.btn_others.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_others.setCheckable(False)
        self.btn_others.setObjectName("btn_others")
        self.btn_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filling.setGeometry(QtCore.QRect(860, 360, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_filling.setFont(font)
        self.btn_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_filling.setCheckable(False)
        self.btn_filling.setObjectName("btn_filling")
        self.btn_path_dayWeek_pie = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek_pie.setGeometry(QtCore.QRect(740, 310, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek_pie.setFont(font)
        self.btn_path_dayWeek_pie.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek_pie.setCheckable(False)
        self.btn_path_dayWeek_pie.setObjectName("btn_path_dayWeek_pie")
        self.btn_pie = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pie.setGeometry(QtCore.QRect(860, 140, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pie.setFont(font)
        self.btn_pie.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_pie.setCheckable(False)
        self.btn_pie.setObjectName("btn_pie")
        self.lineEdit_ost_cakes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ost_cakes.setEnabled(False)
        self.lineEdit_ost_cakes.setGeometry(QtCore.QRect(20, 510, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_ost_cakes.setFont(font)
        self.lineEdit_ost_cakes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_ost_cakes.setStyleSheet("padding-left: 5px")
        self.lineEdit_ost_cakes.setObjectName("lineEdit_ost_cakes")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(860, 580, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit.setCheckable(False)
        self.btn_exit.setObjectName("btn_exit")
        self.btn_path_dayWeek_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek_bakery.setGeometry(QtCore.QRect(740, 210, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek_bakery.setFont(font)
        self.btn_path_dayWeek_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek_bakery.setCheckable(False)
        self.btn_path_dayWeek_bakery.setObjectName("btn_path_dayWeek_bakery")
        self.btn_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bakery.setGeometry(QtCore.QRect(860, 30, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_bakery.setFont(font)
        self.btn_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_bakery.setCheckable(False)
        self.btn_bakery.setObjectName("btn_bakery")
        self.label_ost_filling = QtWidgets.QLabel(self.centralwidget)
        self.label_ost_filling.setEnabled(False)
        self.label_ost_filling.setGeometry(QtCore.QRect(20, 580, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_ost_filling.setFont(font)
        self.label_ost_filling.setObjectName("label_ost_filling")
        WindowBakery.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowBakery)
        QtCore.QMetaObject.connectSlotsByName(WindowBakery)

    def retranslateUi(self, WindowBakery):
        _translate = QtCore.QCoreApplication.translate
        WindowBakery.setWindowTitle(_translate("WindowBakery", "Настройка работы с Выпечкой"))
        self.label_OLAP_dayWeek_cakes.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам по дням недели - торты"))
        self.label_OLAP_dayWeek_pie.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам по дням недели - пирожные"))
        self.label_OLAP_P.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам"))
        self.btn_cakes.setText(_translate("WindowBakery", "???"))
        self.btn_path_ost_cakes.setText(_translate("WindowBakery", "..."))
        self.btn_path_ost_filling.setText(_translate("WindowBakery", "..."))
        self.btn_path_OLAP_P.setText(_translate("WindowBakery", "..."))
        self.label_settings_title.setText(_translate("WindowBakery", "Настройка подключения внешних данных"))
        self.label_ost_cakes.setText(_translate("WindowBakery", "Укажите путь к Остаткам по складам - торты"))
        self.btn_path_dayWeek_cakes.setText(_translate("WindowBakery", "..."))
        self.label_OLAP_dayWeek_bakery.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам по дням недели - выпечка"))
        self.btn_others.setText(_translate("WindowBakery", "???"))
        self.btn_filling.setText(_translate("WindowBakery", "???"))
        self.btn_path_dayWeek_pie.setText(_translate("WindowBakery", "..."))
        self.btn_pie.setText(_translate("WindowBakery", "???"))
        self.btn_exit.setText(_translate("WindowBakery", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_path_dayWeek_bakery.setText(_translate("WindowBakery", "..."))
        self.btn_bakery.setText(_translate("WindowBakery", "КОЭФФИЦИЕНТЫ"))
        self.label_ost_filling.setText(_translate("WindowBakery", "Укажите путь к Остаткам по складам - начинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowBakery = QtWidgets.QMainWindow()
    ui = Ui_WindowBakery()
    ui.setupUi(WindowBakery)
    WindowBakery.show()
    sys.exit(app.exec())
