# Form implementation generated from reading ui file 'bakery.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowBakery(object):
    def setupUi(self, WindowBakery):
        WindowBakery.setObjectName("WindowBakery")
        WindowBakery.resize(1240, 700)
        WindowBakery.setMinimumSize(QtCore.QSize(1240, 700))
        WindowBakery.setMaximumSize(QtCore.QSize(1240, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowBakery.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowBakery)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_OLAP_dayWeek_bakery = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek_bakery.setEnabled(False)
        self.lineEdit_OLAP_dayWeek_bakery.setGeometry(QtCore.QRect(20, 210, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek_bakery.setFont(font)
        self.lineEdit_OLAP_dayWeek_bakery.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek_bakery.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek_bakery.setObjectName("lineEdit_OLAP_dayWeek_bakery")
        self.label_OLAP_P = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_P.setGeometry(QtCore.QRect(20, 80, 771, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_P.setFont(font)
        self.label_OLAP_P.setObjectName("label_OLAP_P")
        self.lineEdit_OLAP_P = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_P.setEnabled(False)
        self.lineEdit_OLAP_P.setGeometry(QtCore.QRect(20, 110, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_P.setFont(font)
        self.lineEdit_OLAP_P.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_P.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_P.setObjectName("lineEdit_OLAP_P")
        self.btn_path_OLAP_P = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_OLAP_P.setGeometry(QtCore.QRect(740, 110, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_OLAP_P.setFont(font)
        self.btn_path_OLAP_P.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_OLAP_P.setCheckable(False)
        self.btn_path_OLAP_P.setObjectName("btn_path_OLAP_P")
        self.label_settings_title = QtWidgets.QLabel(self.centralwidget)
        self.label_settings_title.setGeometry(QtCore.QRect(20, 10, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.label_OLAP_dayWeek_bakery = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek_bakery.setGeometry(QtCore.QRect(20, 180, 771, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek_bakery.setFont(font)
        self.label_OLAP_dayWeek_bakery.setObjectName("label_OLAP_dayWeek_bakery")
        self.btn_exit_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_bakery.setGeometry(QtCore.QRect(860, 580, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit_bakery.setFont(font)
        self.btn_exit_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit_bakery.setCheckable(False)
        self.btn_exit_bakery.setObjectName("btn_exit_bakery")
        self.btn_path_dayWeek_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek_bakery.setGeometry(QtCore.QRect(740, 210, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek_bakery.setFont(font)
        self.btn_path_dayWeek_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek_bakery.setCheckable(False)
        self.btn_path_dayWeek_bakery.setObjectName("btn_path_dayWeek_bakery")
        self.btn_koeff_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_koeff_bakery.setGeometry(QtCore.QRect(860, 30, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_koeff_bakery.setFont(font)
        self.btn_koeff_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_koeff_bakery.setCheckable(False)
        self.btn_koeff_bakery.setObjectName("btn_koeff_bakery")
        WindowBakery.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowBakery)
        QtCore.QMetaObject.connectSlotsByName(WindowBakery)

    def retranslateUi(self, WindowBakery):
        _translate = QtCore.QCoreApplication.translate
        WindowBakery.setWindowTitle(_translate("WindowBakery", "Настройка работы с Выпечкой"))
        self.label_OLAP_P.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам"))
        self.btn_path_OLAP_P.setText(_translate("WindowBakery", "..."))
        self.label_settings_title.setText(_translate("WindowBakery", "Настройка подключения внешних данных"))
        self.label_OLAP_dayWeek_bakery.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам по дням недели - выпечка"))
        self.btn_exit_bakery.setText(_translate("WindowBakery", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_path_dayWeek_bakery.setText(_translate("WindowBakery", "..."))
        self.btn_koeff_bakery.setText(_translate("WindowBakery", "КОЭФФИЦИЕНТЫ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowBakery = QtWidgets.QMainWindow()
    ui = Ui_WindowBakery()
    ui.setupUi(WindowBakery)
    WindowBakery.show()
    sys.exit(app.exec())
