# Form implementation generated from reading ui file 'cake.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowCake(object):
    def setupUi(self, WindowCake):
        WindowCake.setObjectName("WindowCake")
        WindowCake.resize(1240, 700)
        WindowCake.setMinimumSize(QtCore.QSize(1240, 700))
        WindowCake.setMaximumSize(QtCore.QSize(1240, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowCake.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowCake)
        self.centralwidget.setObjectName("centralwidget")
        self.label_OLAP_dayWeek_cakes = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek_cakes.setEnabled(False)
        self.label_OLAP_dayWeek_cakes.setGeometry(QtCore.QRect(20, 380, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek_cakes.setFont(font)
        self.label_OLAP_dayWeek_cakes.setObjectName("label_OLAP_dayWeek_cakes")
        self.label_OLAP_P = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_P.setGeometry(QtCore.QRect(20, 80, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_P.setFont(font)
        self.label_OLAP_P.setObjectName("label_OLAP_P")
        self.lineEdit_OLAP_P = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_P.setEnabled(False)
        self.lineEdit_OLAP_P.setGeometry(QtCore.QRect(20, 110, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_P.setFont(font)
        self.lineEdit_OLAP_P.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_P.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_P.setObjectName("lineEdit_OLAP_P")
        self.btn_path_ost_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_ost_cakes.setGeometry(QtCore.QRect(740, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_ost_cakes.setFont(font)
        self.btn_path_ost_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_ost_cakes.setCheckable(False)
        self.btn_path_ost_cakes.setObjectName("btn_path_ost_cakes")
        self.btn_path_OLAP_P = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_OLAP_P.setGeometry(QtCore.QRect(740, 110, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_OLAP_P.setFont(font)
        self.btn_path_OLAP_P.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_OLAP_P.setCheckable(False)
        self.btn_path_OLAP_P.setObjectName("btn_path_OLAP_P")
        self.label_settings_title = QtWidgets.QLabel(self.centralwidget)
        self.label_settings_title.setGeometry(QtCore.QRect(20, 10, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.label_ost_cakes = QtWidgets.QLabel(self.centralwidget)
        self.label_ost_cakes.setEnabled(False)
        self.label_ost_cakes.setGeometry(QtCore.QRect(20, 480, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_ost_cakes.setFont(font)
        self.label_ost_cakes.setObjectName("label_ost_cakes")
        self.lineEdit_OLAP_dayWeek_cakes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek_cakes.setEnabled(False)
        self.lineEdit_OLAP_dayWeek_cakes.setGeometry(QtCore.QRect(20, 410, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek_cakes.setFont(font)
        self.lineEdit_OLAP_dayWeek_cakes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek_cakes.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek_cakes.setObjectName("lineEdit_OLAP_dayWeek_cakes")
        self.btn_path_dayWeek_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek_cakes.setGeometry(QtCore.QRect(740, 410, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek_cakes.setFont(font)
        self.btn_path_dayWeek_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek_cakes.setCheckable(False)
        self.btn_path_dayWeek_cakes.setObjectName("btn_path_dayWeek_cakes")
        self.lineEdit_ost_cakes = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ost_cakes.setEnabled(False)
        self.lineEdit_ost_cakes.setGeometry(QtCore.QRect(20, 510, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_ost_cakes.setFont(font)
        self.lineEdit_ost_cakes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_ost_cakes.setStyleSheet("padding-left: 5px")
        self.lineEdit_ost_cakes.setObjectName("lineEdit_ost_cakes")
        self.btn_exit_cake = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_cake.setGeometry(QtCore.QRect(860, 580, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit_cake.setFont(font)
        self.btn_exit_cake.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit_cake.setCheckable(False)
        self.btn_exit_cake.setObjectName("btn_exit_cake")
        self.btn_koeff_cake = QtWidgets.QPushButton(self.centralwidget)
        self.btn_koeff_cake.setGeometry(QtCore.QRect(860, 30, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_koeff_cake.setFont(font)
        self.btn_koeff_cake.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_koeff_cake.setCheckable(False)
        self.btn_koeff_cake.setObjectName("btn_koeff_cake")
        WindowCake.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowCake)
        QtCore.QMetaObject.connectSlotsByName(WindowCake)

    def retranslateUi(self, WindowCake):
        _translate = QtCore.QCoreApplication.translate
        WindowCake.setWindowTitle(_translate("WindowCake", "Настройка работы с Торами"))
        self.label_OLAP_dayWeek_cakes.setText(_translate("WindowCake", "Укажите путь к OLAP отчету по продажам по дням недели - торты"))
        self.label_OLAP_P.setText(_translate("WindowCake", "Укажите путь к OLAP отчету по продажам"))
        self.btn_path_ost_cakes.setText(_translate("WindowCake", "..."))
        self.btn_path_OLAP_P.setText(_translate("WindowCake", "..."))
        self.label_settings_title.setText(_translate("WindowCake", "Настройка подключения внешних данных"))
        self.label_ost_cakes.setText(_translate("WindowCake", "Укажите путь к Остаткам по складам - торты"))
        self.btn_path_dayWeek_cakes.setText(_translate("WindowCake", "..."))
        self.btn_exit_cake.setText(_translate("WindowCake", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_koeff_cake.setText(_translate("WindowCake", "КОЭФФИЦИЕНТЫ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowCake = QtWidgets.QMainWindow()
    ui = Ui_WindowCake()
    ui.setupUi(WindowCake)
    WindowCake.show()
    sys.exit(app.exec())
