# Form implementation generated from reading ui file 'filling.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowFilling(object):
    def setupUi(self, WindowFilling):
        WindowFilling.setObjectName("WindowFilling")
        WindowFilling.resize(1240, 700)
        WindowFilling.setMinimumSize(QtCore.QSize(1240, 700))
        WindowFilling.setMaximumSize(QtCore.QSize(1240, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowFilling.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowFilling)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_path_ost_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_ost_filling.setGeometry(QtCore.QRect(740, 610, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_ost_filling.setFont(font)
        self.btn_path_ost_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_ost_filling.setCheckable(False)
        self.btn_path_ost_filling.setObjectName("btn_path_ost_filling")
        self.label_settings_title = QtWidgets.QLabel(self.centralwidget)
        self.label_settings_title.setGeometry(QtCore.QRect(20, 10, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.lineEdit_ost_filling = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ost_filling.setEnabled(False)
        self.lineEdit_ost_filling.setGeometry(QtCore.QRect(20, 610, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_ost_filling.setFont(font)
        self.lineEdit_ost_filling.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_ost_filling.setStyleSheet("padding-left: 5px")
        self.lineEdit_ost_filling.setObjectName("lineEdit_ost_filling")
        self.btn_exit_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_filling.setGeometry(QtCore.QRect(860, 580, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit_filling.setFont(font)
        self.btn_exit_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit_filling.setCheckable(False)
        self.btn_exit_filling.setObjectName("btn_exit_filling")
        self.btn_koeff_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_koeff_filling.setGeometry(QtCore.QRect(860, 30, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_koeff_filling.setFont(font)
        self.btn_koeff_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_koeff_filling.setCheckable(False)
        self.btn_koeff_filling.setObjectName("btn_koeff_filling")
        self.label_ost_filling = QtWidgets.QLabel(self.centralwidget)
        self.label_ost_filling.setEnabled(False)
        self.label_ost_filling.setGeometry(QtCore.QRect(20, 580, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_ost_filling.setFont(font)
        self.label_ost_filling.setObjectName("label_ost_filling")
        WindowFilling.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowFilling)
        QtCore.QMetaObject.connectSlotsByName(WindowFilling)

    def retranslateUi(self, WindowFilling):
        _translate = QtCore.QCoreApplication.translate
        WindowFilling.setWindowTitle(_translate("WindowFilling", "Настройка работы с Начинкой"))
        self.btn_path_ost_filling.setText(_translate("WindowFilling", "..."))
        self.label_settings_title.setText(_translate("WindowFilling", "Настройка подключения внешних данных"))
        self.btn_exit_filling.setText(_translate("WindowFilling", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_koeff_filling.setText(_translate("WindowFilling", "КОЭФФИЦИЕНТЫ"))
        self.label_ost_filling.setText(_translate("WindowFilling", "Укажите путь к Остаткам по складам - начинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowFilling = QtWidgets.QMainWindow()
    ui = Ui_WindowFilling()
    ui.setupUi(WindowFilling)
    WindowFilling.show()
    sys.exit(app.exec())
