# Form implementation generated from reading ui file 'viborRazdela.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowsViborRazdela(object):
    def setupUi(self, WindowsViborRazdela):
        WindowsViborRazdela.setObjectName("WindowsViborRazdela")
        WindowsViborRazdela.resize(370, 540)
        WindowsViborRazdela.setMinimumSize(QtCore.QSize(370, 540))
        WindowsViborRazdela.setMaximumSize(QtCore.QSize(370, 540))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowsViborRazdela.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowsViborRazdela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bakery.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_bakery.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_bakery.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_bakery.setFont(font)
        self.btn_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_bakery.setCheckable(False)
        self.btn_bakery.setObjectName("btn_bakery")
        self.verticalLayout.addWidget(self.btn_bakery)
        self.btn_cakes = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cakes.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_cakes.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_cakes.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cakes.setFont(font)
        self.btn_cakes.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_cakes.setCheckable(False)
        self.btn_cakes.setObjectName("btn_cakes")
        self.verticalLayout.addWidget(self.btn_cakes)
        self.btn_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filling.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_filling.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_filling.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_filling.setFont(font)
        self.btn_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_filling.setCheckable(False)
        self.btn_filling.setObjectName("btn_filling")
        self.verticalLayout.addWidget(self.btn_filling)
        self.btn_others = QtWidgets.QPushButton(self.centralwidget)
        self.btn_others.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_others.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_others.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_others.setFont(font)
        self.btn_others.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_others.setCheckable(False)
        self.btn_others.setObjectName("btn_others")
        self.verticalLayout.addWidget(self.btn_others)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_exit.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_exit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit.setCheckable(False)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        WindowsViborRazdela.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowsViborRazdela)
        QtCore.QMetaObject.connectSlotsByName(WindowsViborRazdela)

    def retranslateUi(self, WindowsViborRazdela):
        _translate = QtCore.QCoreApplication.translate
        WindowsViborRazdela.setWindowTitle(_translate("WindowsViborRazdela", "Выбор раздела"))
        self.label_title.setText(_translate("WindowsViborRazdela", "Выберите раздел"))
        self.btn_bakery.setText(_translate("WindowsViborRazdela", "ВЫПЕЧКА"))
        self.btn_cakes.setText(_translate("WindowsViborRazdela", "ТОРТЫ"))
        self.btn_filling.setText(_translate("WindowsViborRazdela", "НАЧИНКИ"))
        self.btn_others.setText(_translate("WindowsViborRazdela", "ОСТАЛЬНОЕ"))
        self.btn_exit.setText(_translate("WindowsViborRazdela", "ВЫХОД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowsViborRazdela = QtWidgets.QMainWindow()
    ui = Ui_WindowsViborRazdela()
    ui.setupUi(WindowsViborRazdela)
    WindowsViborRazdela.show()
    sys.exit(app.exec())
